agents = [
    {'name': 'id', 'type': 'BIGINT'},
    {'name': 'available', 'type': 'BOOLEAN'},
    {'name': 'occasional', 'type': 'BOOLEAN'},
    {'name': 'created_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'contact_active', 'type': 'BOOLEAN'},
    {'name': 'mobile', 'type': 'VARCHAR'},
    {'name': 'description', 'type': 'varchar(255)'},
    {'name': 'contact_name', 'type': 'VARCHAR(255)'},
    {"name": "available_since", 'type': "VARCHAR(255)"},
    {"name": "contact_last_login_at", 'type': "TIMESTAMP WITH TIME ZONE"},
    {"name": "contact_created_at", 'type': "TIMESTAMP WITH TIME ZONE"},
    {"name": "contact_email", 'type': "VARCHAR(255)"},
    {"name": "contact_phone", 'type': "VARCHAR(255)"},
    {"name": "contact_mobile", 'type': "VARCHAR(255)"},
    {"name": "contact_language", 'type': "VARCHAR(255)"},
    {"name": "contact_job_title", 'type': "VARCHAR(255)"},
    {"name": "contact_time_zone", 'type': "VARCHAR(255)"},
    {"name": "contact_updated_at", 'type': "TIMESTAMP WITH TIME ZONE"},
    {"name": "signature", 'type': "VARCHAR(255)"},
    {"name": "ticket_scope", 'type': "INT"},
    {"name": "updated_at", 'type': "TIMESTAMP WITH TIME ZONE"},
],
