contacts = [
    {'name': 'id', 'type': 'BIGINT'},
    {'name': 'created_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'updated_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'active', 'type': 'BOOLEAN'},
    {'name': 'mobile', 'type': 'VARCHAR'},
    {'name': 'time_zone', 'type': 'VARCHAR(255)'},
    {'name': 'phone', 'type': 'VARCHAR(255)'},
    {'name': 'description', 'type': 'VARCHAR(255)'},
    {'name': 'company_id', 'type': 'VARCHAR(255)'},
    {'name': 'language', 'type': 'VARCHAR(255)'},
    {'name': 'name', 'type': 'VARCHAR(255)'},
    {'name': 'email', 'type': 'VARCHAR(255)'},
    {'name': 'address', 'type': 'VARCHAR(255)'},
    {'name': 'twitter_id', 'type': 'VARCHAR(255)'},
    {'name': 'job_title', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_lead_source', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_applicant_type', 'type': 'VARCHAR'},
    {'name': 'custom_fields_applicant_id', 'type': 'BIGINT'},
    {'name': 'custom_fields_customer_longevity', 'type': 'VARCHAR'},
    {'name': 'custom_fields_assigned_agent', 'type': 'VARCHAR'},
    {'name': 'custom_fields_county', 'type': 'VARCHAR'},
    {'name': 'custom_fields_coapplicant_id', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_home_phone', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_vip', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_address_line_1', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_relation', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_first_name', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_last_name', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_nickname', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_state', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_city', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_account_type', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_gender', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_unit_number', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_alternate_email', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_plus4', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_address_line_2', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_zip_code', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields_marrital_status', 'type': 'VARCHAR(255)'}
]
