tickets = [
    {'name': 'id', 'type': 'BIGINT'},
    {'name': 'reply_cc_emails', 'type': 'VARCHAR(255)'},
    {'name': 'is_escalated', 'type': 'BOOLEAN'},
    {'name': 'updated_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'created_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'group_id', 'type': 'BIGINT'},
    {'name': 'requester_id', 'type': 'BIGINT'},
    {'name': 'fr_escalated', 'type': 'BOOLEAN'},
    {'name': 'source', 'type': 'VARCHAR(255)'},
    {'name': 'responder_id', 'type': 'BIGINT'},
    {'name': 'cc_emails', 'type': 'VARCHAR(255)'},
    {'name': 'subject', 'type': 'VARCHAR(255)'},
    {'name': 'due_by', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'type', 'type': 'VARCHAR(255)'},
    {'name': 'company_id', 'type': 'VARCHAR(255)'},
    {'name': 'status', 'type': 'BIGINT'},
    {'name': 'fr_due_by', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'to_emails', 'type': 'VARCHAR(255)'},
    {'name': 'product_id', 'type': 'VARCHAR(255)'},
    {'name': 'custom_fields', 'type': 'VARCHAR(255)'},
    {'name': 'description_text', 'type': 'VARCHAR(255)'},
    {'name': 'spam', 'type': 'BOOLEAN'},
    {'name': 'email_config_id', 'type': 'VARCHAR(255)'},
    {'name': 'fwd_emails', 'type': 'VARCHAR(255)'},
    {'name': 'priority', 'type': 'INT'},
    {'name': 'description', 'type': 'VARCHAR(10240)'}
]
